import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=n=>JSON.parse(fs.readFileSync(path.join(root,'data',n),'utf8').replace(/^\uFEFF/,''));
const base=read('sigs.json'), editorial=read('editorial.json');
const checks=fs.existsSync(path.join(root,'data/checks.json'))?read('checks.json'):{checkedAt:null,sources:[]};
const updates=fs.existsSync(path.join(root,'data/updates.json'))?read('updates.json'):[];
const events=fs.existsSync(path.join(root,'data/events.json'))?read('events.json'):[];
const payload={...base,editorial,checks,updates,events};
const text=JSON.stringify(payload,null,2);
if(!base.sigs.length||new Set(base.sigs.map(s=>s.acronym)).size!==base.sigs.length)throw Error('Invalid SIG identities');
if(/https?:\/\/(www\.)?synsig\.org/i.test(text))throw Error('Blocked obsolete domain');
if(/[A-Z]:\\\\Users|GMAIL_APP_PASSWORD|AIza[\w-]{20}|BEGIN PRIVATE KEY/.test(text))throw Error('Private material in public data');
fs.writeFileSync(path.join(root,'dist/data.json'),text+'\n');
const output=path.join(root,'docs');
fs.mkdirSync(output,{recursive:true});
for(const name of ['index.html','style.css','app.js','data.json'])fs.copyFileSync(path.join(root,'dist',name),path.join(output,name));
fs.writeFileSync(path.join(output,'.nojekyll'),'');
console.log(JSON.stringify({groups:base.sigs.length,series:editorial.series.length,recordings:base.sigs.reduce((n,s)=>n+s.videos.length,0),events:events.length,checkSources:checks.sources.length}));
